sudo: required
services:
  - docker

before_install:
  - docker build -t aeroslon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vba/react-test npm run test

after_success:
  - docker build -t aeroslon/multi-client -f ./client
  - docker build -t aeroslon/multi-server -f ./server
  - docker build -t aeroslon/multi-worker -f ./worker
  - docker build -t aeroslon/multi-ngnix -f ./ngnix
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push aeroslon/multi-client
  - docker push aeroslon/multi-server
  - docker push aeroslon/multi-worker
  - docker push aeroslon/multi-ngnix
