sudo: required
services:
  - docker

before_install:
  - docker build -t aeroslon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aeroslon/react-test npm run test

after_success:
  - docker build -t aeroslon/multi-client ./client
  - docker build -t aeroslon/multi-server ./server
  - docker build -t aeroslon/multi-worker ./worker
  - docker build -t aeroslon/multi-nginx ./nginx
  # login to docker cli
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # push images to docker hub
  - docker push aeroslon/multi-client
  - docker push aeroslon/multi-server
  - docker push aeroslon/multi-worker
  - docker push aeroslon/multi-nginx

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-592315381426"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
