sudo: required
services:
  - docker

before_install:
  - docker build -t aeroslon/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aeroslon/react-test npm run test

after_success:
  - docker build -t aeroslon/multi-client ./client
  - docker build -t aeroslon/multi-server ./server
  - docker build -t aeroslon/multi-worker ./worker
  - docker build -t aeroslon/multi-ngnix ./ngnix
  # login to docker cli
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # push images to docker hub
  - docker push aeroslon/multi-client
  - docker push aeroslon/multi-server
  - docker push aeroslon/multi-worker
  - docker push aeroslon/multi-ngnix
